theme: just-the-docs

title: OpenFLAME

# Set a path/url to a favicon that will be displayed by the browser
favicon_ico: "/assets/images/favicon.ico"

logo: "/assets/images/logo_horizontal.png"

# Set the destination directory
# destination: ./docs

# Define collections
collections:
  - people

# Confifure callouts
callouts:
  important:
    title: Important
    color: blue
  highlight:
    color: yellow
  hint:
    title: Hint
    color: green
  warning:
    title: Warning
    color: red

sass:
  quiet_deps: true # https://github.com/just-the-docs/just-the-docs/issues/1541
  silence_deprecations: ["import"] # https://github.com/just-the-docs/just-the-docs/issues/1607
